name: AI Assistant Actions
on:
  repository_dispatch:
    types: [ai_update]
  workflow_dispatch:
    inputs:
      file_path:
        description: 'File to modify'
        required: true
      commit_message:
        description: 'Commit message'
        required: true
      content:
        description: 'New content'
        required: true

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update File
        env:
          FILE_PATH: ${{ github.event.inputs.file_path }}
          COMMIT_MSG: ${{ github.event.inputs.commit_message }}
          NEW_CONTENT: ${{ github.event.inputs.content }}
        run: |
          echo "$NEW_CONTENT" > "$FILE_PATH"
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'AI Assistant: ${{ github.event.inputs.commit_message }}'
          body: |
            Automated changes by AI Assistant
            - Modified: ${{ github.event.inputs.file_path }}
          branch: ai-updates
          delete-branch: true